name: Deploy to GitHub Pages on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Получить существующую ветку gh-pages
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages-content

      # Шаг 3: Создать структуру папок
      - name: Prepare deployment
        run: |
          # Создаем основную папку сборки
          mkdir -p build

          # Копируем ВСЕ старые версии из gh-pages в новую сборку
          if [ -d "gh-pages-content" ]; then
            cp -r gh-pages-content/* build/ || true
          fi

          # Создаем новую версионную папку
          mkdir -p build/v${{ github.ref_name }}

          # Копируем текущие файлы в новую версионную папку
          cp -r ./ru ./en ./index.html ./build/v${{ github.ref_name }}/

          # Также обновляем основную (latest) версию
          cp -r ./ru ./en ./index.html ./build/

      # Шаг 4: Развернуть в ветку gh-pages
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: false
